### ISSUE TITLE
The method "await" should be called in an async method

### ISSUE THREAD

**Issue by langhaoabcd** [vipcxj/jasync#14]
未识别到方法是异步方法是什么问题？ jdk11环境，配置如下
![image](https://user-images.githubusercontent.com/39892654/186604753-f7ace55e-b164-4e0f-b0d1-0d28edf0f1b4.png)
![image](https://user-images.githubusercontent.com/39892654/186604965-810dfee1-1a2b-4e87-b7f1-729b611f3134.png)

**Comment by vipcxj** [comment]
jasync是个apt项目，对于maven项目，并且是jdk 8来说，直接放依赖里，jdk就能识别为apt，对于jdk 11，可能需要放annotationPath里才行，至于gradle，我这没现成的项目，你这项目github上有地址吗？或者你用
```groovy
dependencies {
  annotationProcessor "io.github.vipcxj:jasync-core:1.0.12"
}
```

**Comment by langhaoabcd** [comment]
@vipcxj 添加了没啥用，麻烦你写个例子

**Comment by vipcxj** [comment]
@langhaoabcd fixed.
gradle 疑似有个很隐秘的bug，jdk.attach.allowAttachSelf不知为什么默认是true，问题是这是个假的true，正常情况下，这个属性是true的情况下，vm是支持attach自己的，但现实是VM里的jdk.attach.allowAttachSelf是null，而ByteBuddy原本是有对策的，但ByteBuddy看到jdk.attach.allowAttachSelf时true，就认为那个对策不需要了，结果就杯具了~

**Comment by qw623577789** [comment]
我是gradle + jdk17,下面这样写没问题
```
dependencies {
    implementation 'io.github.vipcxj:jasync-core:0.1.11'
    implementation 'io.github.vipcxj:jasync-reactive:0.1.11'

    annotationProcessor 'io.github.vipcxj:jasync-core:0.1.11'
    testAnnotationProcessor 'io.github.vipcxj:jasync-core:0.1.11'
}
```

**Comment by vipcxj** [comment]
@langhaoabcd 
dependencies {
    implementation 'io.github.vipcxj:jasync-core:0.1.11' // 这个改成 implementation 'io.github.vipcxj:jasync-runtime:0.1.11' 因为runtime是core的依赖，所以直接声明core当然也是可以的，但core在运行时其实是不需要的，所以用runtime更好
    implementation 'io.github.vipcxj:jasync-reactive:0.1.11' // 这个我写了，但其实还没测~ 不过理论上不需要额外的库，直接用JPromise.create 或 JPromise.generate 应该也能对接reactive，我写这个库主要是对接更底层的 Publisher和Subscriber

    annotationProcessor 'io.github.vipcxj:jasync-core:0.1.11'
    testAnnotationProcessor 'io.github.vipcxj:jasync-core:0.1.11' // 这个可能不需要，annotationProcessor 好像对test也有效，不过我没试过，所以不是很确定
}
另外问下0.1.13版本是否修复了gradle 插件失效的问题？

**Comment by langhaoabcd** [comment]
用新版本，这样写能运行

implementation 'io.github.vipcxj:jasync-reactive:1.0.12' 
implementation 'io.github.vipcxj:jasync-core:1.0.13' 
annotationProcessor 'io.github.vipcxj:jasync-core:1.0.13' 

testAnnotationProcessor 'io.github.vipcxj:jasync-core:1.0.13' }
